### ISSUE TITLE
Parsed 1 DLL then gets this error

### ISSUE THREAD

**Issue by yao88** [BackTrak/DependencyFixup#1]
Unhandled Exception: System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NewNormalizePath(String path, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.GetFullPathInternal(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at DependencyFixup.Program.FixupConfigFiles(String redirectAssemblyName, String configFilePatten)
   at DependencyFixup.Program.Run(String[] args)
   at DependencyFixup.Program.Main(String[] args)

**Comment by BackTrak** [comment]
Sorry for the late response, could you please supply the full path to the executable that you were trying to analyze?

**Comment by BackTrak** [comment]
Closing due to inactivity.

**Comment by BackTrak** [comment]
Closing due to inactivity.
